### ISSUE TITLE
[rViz] panels do not show up consistently

### ISSUE THREAD

**Issue by kejxu** [ms-iot/ROSOnWindows#10]

**Comment by ooeygui** [comment]
There appears to be a race condition in rViz. While this repros on Linux, it repros much more consistently on Windows.

Repro:
rosrun rviz rviz

Observe:
inconsistently, one or more of the default panels will not display.

Expect:
All default panels to display.

Suspect a race condition between async creation of the backing windows during window state restore.

**Comment by seanyen-msft** [comment]
https://answers.ros.org/question/315664/ros-not-running-well-on-windows-10/
