### ISSUE TITLE
[navigation][map_server] catkin build: missing libgen.h

### ISSUE THREAD

**Issue by Pyrokine** [ms-iot/ROSOnWindows#101]
when catkin the package, cmd shows that it lacks libgen.h.

**Comment by seanyen** [comment]
@Pyrokine what package are you trying to build?

**Comment by Pyrokine** [comment]
move_server package in the navigation package

**Comment by Pyrokine** [comment]
I comment the wrong name. It's map_server

**Comment by seanyen** [comment]
Hi @Pyrokine, can you share more information where you checkout the source code for `navigation` packages and the steps you took to build?

JFYI, as of today, the Windows build `navigation` code is in `ms-iot` fork: https://github.com/ms-iot/navigation/tree/init_windows, and the upstream repository doesn't have the ported changes yet (but the PRs are out, awaiting feedback.)

**Comment by Pyrokine** [comment]
Thanks a lot. I built the original package from ros-planning/navigation. I found those package you forked from ros and it works.
