### ISSUE TITLE
Improve launch-prefix handling

### ISSUE THREAD

**Issue by ooeygui** [ms-iot/ROSOnWindows#108]
in a ROSLaunch file, the attribute launch-prefix is used for a variety of things, including launching nodes in a new console and debugging.

On Windows, to open a new console window, you use the cmd.exe intrinsic `start`. calling this seems to strip the command line arguments.

**Comment by gavanderhoorn** [comment]
Keeping things connected: [What is the Windows equivalent of launch-prefix="xterm -e" for launch files?](https://answers.ros.org/question/321596) on ROS Answers.

**Comment by ooeygui** [comment]
Looking to see if the new terminal has this feature.

**Comment by ooeygui** [comment]
We're not going to be adding new features to ROS1; closing
