### ISSUE TITLE
roscore stop because some .dlls not found.

### ISSUE THREAD

**Issue by budongyue** [ms-iot/ROSOnWindows#109]
1when I meet errors,it says that I don't have "defusedxml".So,I install it by using "pip install defusedxml"
2 After following the standard installation instructions, I've been trying to run roscore, but I get the following errors when it gets to starting /rosout:
The code execution cannot proceed because {boost_date_time-vc141-mt-x64-1_66.dll/boost_regex-vc141-mt-x64-1_66.dll/boost_system-vc141-mt-x64-1_66.dll/boost_thread-vc141-mt-x64-1_66.dll/log4cxx.dll} was not found. Reinstalling the program may fix this problem
Is it caused because I install "defusedxml" manually?
What should  I do ?Thanks.

**Comment by seanyen** [comment]
@budongyue According to #110, it seems that `rosdep` failed to be deployed in your environment, therefore the ROS installation cannot pull down those 3rd party binaries automatically. Once #110 is resolved, I would recommend to run `choco upgrade ros-melodic-desktop_full -y --force` again to trigger `rosdep` to run.

For now I will close this issue, and we can reopen it if resolving #110 doesn't help.
