### ISSUE TITLE
[ros-python2] ERROR: The term `cmd` is not recognized as the name of a comlet...

### ISSUE THREAD

**Issue by budongyue** [ms-iot/ROSOnWindows#110]
![%@FUKL)E}2@W)5I5S(JU Y3](https://user-images.githubusercontent.com/45566469/56849855-be147500-692c-11e9-82ec-900e42c5dc22.png)

**Comment by gavanderhoorn** [comment]
Appears to be a cross-post of [Error while running 'C:\ProgramData\chocolatey\lib\ros-python2\tools\chocolateyinstall.ps1'](https://answers.ros.org/question/322035) on ROS Answers.

**Comment by seanyen** [comment]
@budongyue can you do `set ComSpec` and `where cmd` to see if `cmd.exe` visible in your command prompt? Usually it exists at `c:\windows\syetem32\cmd.exe`.

**Comment by ooeygui** [comment]
Investigating.

**Comment by ooeygui** [comment]
@seanyen We should use the %comspec% variable in the install scripts in case the path isn't set correctly.

**Comment by ooeygui** [comment]
Confirmed that this is environment specific. It does not repro on clean installs or upgrades.

**Comment by budongyue** [comment]
@seanyen Yes,I can see the cmd after do set ComSpec and where cmd

**Comment by seanyen** [comment]
@budongyue Thanks for the confirm. I have updated the `ros-python2` package to use `%ComSpec%` to run batch scripts. Can you run again `choco upgrade ros-python2 -y` to see if you still see the error?

**Comment by ooeygui** [comment]
Please reopen if this isn't fixed for you
