### ISSUE TITLE
Rosdep: Suitesparse cannot be used as a rosdep

### ISSUE THREAD

**Issue by ooeygui** [ms-iot/ROSOnWindows#119]
Suitesparse is currently built by vcpkg which does not put cmake files into a location which is usable by ros nodes. The previous version is. If you require suitesparse, please downgrade until we can implement the correct fix.

`choco install suitesparse --version  1.4.0.20180908 --allow-downgrade`

**Comment by seanyen** [comment]
The `sutesparse` now is mapped to the `vcpkg` port and that should fix this issue. https://github.com/ms-iot/rosdistro-db/pull/44

I'm closing this issue now.
