### ISSUE TITLE
Developing ROSpackage in VIsual Studio

### ISSUE THREAD

**Issue by Brabalawuka** [ms-iot/ROSOnWindows#131]
**Describe the bug**
I am a rookie and it may be due to my misoperation. May I ask is there any way to get a intellisence when I create a .cpp file under the new package src folder?

**To Reproduce**
-Create a new package in command line  
-Open devenv and create a new cpp node  
-The new cpp file is not getting inteliience such as when including header files  

**Environment information:**
 - OS version: `windows 10 1903`
 - Chocolatey Versions: `choco list --local-only`

**Comment by Brabalawuka** [comment]
Fixed by adding lines in Cmakelist.txt

**Comment by seanyen** [comment]
@Brabalawuka Do you mind to share the lines you added in `CMakeLists.txt`? It might help for others who are also running into the same issue.

**Comment by Brabalawuka** [comment]
Haha is it a simple solution just remember to

`add_executable(@packagename src/@filename.cpp)`
