### ISSUE TITLE
Installation failure when it is running under an account name with spaces

### ISSUE THREAD

**Issue by seanyen** [ms-iot/ROSOnWindows#134]
**How to repro:**
1. Create a local account name like `test user`.
2. Follow the [steps](https://wiki.ros.org/Installation/Windows) to install ROS.

**Expected Behavior:**
ROS is installed successfully.

**Actual Behavior:**
Chocolatey outputs the following errors:
```
running rosdep...
"Could not create temporary file: C:\Users\test user\AppData\Local\Temp\chocolatey\setup.18575061.bat"
 The upgrade of ros-melodic-desktop_full was successful.
  Software installed to 'c:\opt\ros'
```

**Workaround:**
1. Create another local account name without spaces.
2. Configure the newly created local account as administrator.
3. Run the installation again after signing in the newly created account.

**Comment by ooeygui** [comment]
Closing this. Our recommendation is operating within c:\opt and root workspaces without a space in the name
