### ISSUE TITLE
ROSBag - ImportError: No module named Crypto

### ISSUE THREAD

**Issue by ooeygui** [ms-iot/ROSOnWindows#144]
This is a cross-post for https://answers.ros.org/question/331160/importerror-no-module-named-crypto/.

Traceback (most recent call last):
  File "C:\opt\ros\melodic\x64\bin\rosbag", line 34, in <module>
    import rosbag
  File "C:\opt\ros\melodic\x64\lib\site-packages\rosbag\__init__.py", line 33, in <module>
    from .bag import Bag, Compression, ROSBagException, ROSBagFormatException, ROSBagUnindexedException
  File "C:\opt\ros\melodic\x64\lib\site-packages\rosbag\bag.py", line 53, in <module>
    from Crypto import Random
ImportError: No module named Crypto
we tried installing Crypto and pycrypto manually, which all come back as successfull, but the error persists

**Comment by seanyen** [comment]
Now the `ros_comm` moved to use `pycryptodome` (https://github.com/ros/ros_comm/pull/1609) and I authored that in the rosdistro-db (https://github.com/ms-iot/rosdistro-db/pull/42). I verified it is no longer reproduced in the latest prerelease, so I am closing it.
