### ISSUE TITLE
Cannot build a workspace containing more than 100 packages

### ISSUE THREAD

**Issue by ghost** [ms-iot/ROSOnWindows#148]
**Describe the bug**
Launching the command `catkin_make` on a workspace containing more than 100 packages doesn't work. The outcome is an infinite exception printed on the console: `ImportError: No module named catkin_make`

**To Reproduce**
* Catkin workspace setup instructions
  * Create a workspace folder `C:\ws\maplab\`. Inside it, create the `src` folder
  * Inside the `src` folder run: 
    * `git clone https://github.com/ethz-asl/maplab  --recurse` 
    *  `git clone https://github.com/ethz-asl/maplab_dependencies --recurse`
  * Launch command `catkin_init_workspace`
  * `cd C:\ws\maplab\`
  * Launch command `catkin_make --source .`

**Expected behavior**
The `catkin_make` command should succeed, as it does on Ubuntu

**Workaround**
The issue is related to the fact that Catkin tries to parallelise the build process when there are more than 100 packages. As a workaround, I disabled this feature. To do so, edit the file `C:\opt\python27amd64\Lib\site-packages\catkin_pkg\packages.py`; inside the function `find_packages_allowing_duplicates`, set `parallel = False` (instead of `parallel = len(data) > 100`)

**Environment information:**
 - OS version: `Windows 10 Version 1903 (OS Build 18362.295)`
 - Chocolatey Versions:

    <details><summary>Chocolatey v0.10.15</summary>
    <p> 
    <br/>assimp 4.0.1.1809242322
    <br/>boost 1.66.0.1904102339
    <br/>bullet3 2.87.0.1809242326
    <br/>bzip2 1.0.6.1901242108
    <br/>chocolatey 0.10.15
    <br/>chocolatey-core.extension 1.3.3
    <br/>chocolatey-windowsupdate.extension 1.0.4
    <br/>console_bridge 0.4.0.1809242322
    <br/>cppunit 1.12.1.1809242322
    <br/>cppzmq 4.2.2.1811162207
    <br/>dlfcn-win32 1.1.1.1811162226
    <br/>eigen 3.3.4.1809242322
    <br/>freeimage 3.17.0.1811160037
    <br/>gazebo9 9.4.1.1903240636
    <br/>google-mock 1.8.0.1809242326
    <br/>google-test 1.8.0.1809242322
    <br/>gtk2 2.22.1.1904131648
    <br/>hg 5.1
    <br/>ilmbase 2.2.1.1811210800
    <br/>jasper 2.0.14.1811210919
    <br/>jxrlib 1.1.0.1811210809
    <br/>KB2919355 1.0.20160915
    <br/>KB2919442 1.0.20160915
    <br/>KB2999226 1.0.20181019
    <br/>KB3033929 1.0.5
    <br/>KB3035131 1.0.3
    <br/>lcms 2.8.0.1811210903
    <br/>libcurl 7.58.0.1809242322
    <br/>libflann 1.9.1.1809090720
    <br/>libgraphviz 2.41.0.1810022039
    <br/>libjpeg-turbo 1.5.3.1809242322
    <br/>liblzma 5.2.4.1811210837
    <br/>libogg 1.3.3.1809090720
    <br/>libopencv 3.4.1.1809242322
    <br/>libpcl 1.8.1.1809090720
    <br/>libpng 1.6.35.1809242322
    <br/>libraw 0.19.0.1811210804
    <br/>libtbb-dev 2018.6.0.1812011750
    <br/>libtheora 1.1.1.1809090720
    <br/>libwebp 0.6.1.1811210731
    <br/>log4cxx 0.10.0.1809242322
    <br/>lz4 1.8.1.1809242322
    <br/>nodejs 12.8.0
    <br/>nodejs.install 12.8.0
    <br/>ogre 1.10.11.1901312214
    <br/>openexr 2.2.1.1811210832
    <br/>openjpeg 2.3.0.1811210736
    <br/>openssl 1.1.1.1809242322
    <br/>pkg-config 0.29.2.1809242322
    <br/>poco 1.8.1.1809242322
    <br/>protobuf 3.6.1.1811130545
    <br/>pyqt5 5.10.1.1809242322
    <br/>pyside2 5.10.1.1809242322
    <br/>qt5-sdk 5.10.1.1903182340
    <br/>qwt 6.1.3.1811212304
    <br/>ros-catkin-tools 0.0.1.1903221831
    <br/>ros-cmake 3.11.4.1809242322
    <br/>ros-melodic-desktop 20190729.1
    <br/>ros-melodic-desktop_full 20190729.1
    <br/>ros-python2 2.7.15.1904300710
    <br/>ros-vcpkg 2018.11.23.1906112226
    <br/>sbcl 0.0.0.1809242326
    <br/>sdl 1.2.15.1809242322
    <br/>sdl_image 1.2.12.1809242322
    <br/>sip 4.19.8.1809242322
    <br/>tiff 4.0.9.1811210742
    <br/>tinyxml 2.6.2.1809242322
    <br/>tinyxml2 6.1.0.1809242322
    <br/>urdfdom 1.0.0.1809242322
    <br/>urdfdom_headers 1.0.0.1809242322
    <br/>vcpython27 9.0.30729.1809090720
    <br/>vcredist140 14.22.27821
    <br/>yaml-cpp 0.6.2.1901170034
    <br/>zeromq 4.2.5.1811162203
    <br/>zlib 1.2.11.1809242322
    <br/>75 packages installed.
    </p>
    </details>

**Comment by ooeygui** [comment]
I have a repro of this. It looks like the environment isn't getting inherited into the forked processes. I'm working to understand that.

**Comment by ooeygui** [comment]
There are a couple of things contributing to this issue. 
First, this specific workspace includes many sub projects. This isn't an advisable practice as each time you build, the workspace needs to be crawled.

On Windows, there is an environment limit - Each process inherits the host process's environment. The total limit of the entire environment is 32,000 characters - which can be quickly exhausted by Catkin. (https://devblogs.microsoft.com/oldnewthing/20100203-00/?p=15083)

For this bug, we're going to do two things - one try to detect the environment size and warn, then two limit Windows to not parallelize.

It would be ideal if ethz-asl could break up the dependencies so that you do not have to touch them on every build.

**Comment by seanyen** [comment]
Closing it because the fix is merged by the upstream.
