### ISSUE TITLE
[ROS][DevOps] Factor and Document how customers can build and publish binaries

### ISSUE THREAD

**Issue by ooeygui** [ms-iot/ROSOnWindows#149]
ROS on Windows is built using Azure DevOps. We'd like to make it easier for 3rd parties to build their own ROS nodes and publish to chocolaty.

**Comment by roycey** [comment]
Did we not complete this here - https://ms-iot.github.io/ROSOnWindows/GettingStarted/PortingANode.html. Can we close this?

**Comment by ooeygui** [comment]
Yep, good catch
