### ISSUE TITLE
"Input line too long" error during catkin

### ISSUE THREAD

**Issue by johnwason** [ms-iot/ROSOnWindows#157]
**Describe the bug**
When a large number of packages are in the workspace, the environmental variables in setup.bat can become very long and exceed the 8191 characters. 

**To Reproduce**
Have enough packages in the workspace to have $PATH exceep 8191 characters in length.

**Expected behavior**
setup.bat should complete without errors. A better solution to this issue would be to have git bash or powershell used instead of command for ros on windows. cmd is limited and cumbersome compared to the more modern options.

**Environment information:**
 - OS version: `Windows 10`

**Comment by ooeygui** [comment]
I'm going to close this issue since we cannot do anything about path length in Windows command prompt
