### ISSUE TITLE
RViz: PointCloud2 is not correctly displayed

### ISSUE THREAD

**Issue by fujimo-t** [ms-iot/ROSOnWindows#160]
**Describe the bug**
When I displayed pointcloud2 topic by RViz, there are small points in the window.

![image](https://user-images.githubusercontent.com/10286050/67174101-d822a200-f3fb-11e9-99fe-9c702f954734.png)

But color of the pointcloud is black even if it has RGB information. 
Also all option related to appearance such as Size, Color Transformer and Alpha are not working.
There are just small and black points.

And there are same errors repeatedly in terminal:
`[ERROR] [1571627291.667096300, 1120.509000000]: Error: GLHardwareVertexBuffer::lock - failed to Discard the buffer. Try to recreate the buffer  `

This error is similar to #49 and #66 and I notice all of them and I use *Intel graphic*.

**Environment information:**
 - OS version: `Windows 10 ver 1903`
 - Graphic card: `Intel UHD Graphics 620`

**Comment by ooeygui** [comment]
@fujimo-t Thank you for the report. 

We have found that OpenGL driver implementations on Windows are inconsistent. We are investigating using an OpenGL to Direct3D translator, but this is a longer term investment.

Our recommendation for video cards or drivers that manifest rendering is to change the point 'style' to a different setting.
