### ISSUE TITLE
Support for realsense-ros

### ISSUE THREAD

**Issue by chrislgarry** [ms-iot/ROSOnWindows#168]
Is there any support for https://github.com/IntelRealSense/realsense-ros ? 

In an older issue, someone had mentioned Microsoft was working on it:
https://github.com/IntelRealSense/realsense-ros/issues/853

I'd love to develop on Windows but having to port this node myself would be a no-go for me. I want to get realsense data broadcasted from my ROS node on Linux to a ROS node on Windows.

Any advice is appreciated. Thanks!

**Comment by ooeygui** [comment]
I've issued a pull request to Intel - https://github.com/IntelRealSense/realsense-ros/pull/1147. Please feel free to ping that pull request .

I'm going to close this here as this is an external package.
