### ISSUE TITLE
rosrun with python files is not working

### ISSUE THREAD

**Issue by OliHas** [ms-iot/ROSOnWindows#169]
Thank you for the 'Getting started/UsingROSOnWindows' Introduction.

I'm unable to run the following command:
```
c:\catkin_ws>rosrun beginner_tutorials talker.py
[rosrun] Couldn't find executable named talker.py
```
But this works:
```
c:\catkin_ws>rosrun beginner_tutorials scripts/talker.py
```

Regarding the [Python](https://github.com/ms-iot/ROSOnWindows/blob/master/GettingStarted/UsingROSonWindows.md#python) section, it is unclear to me, how I should rename the [python file](https://github.com/ms-iot/ROSOnWindows/blob/master/GettingStarted/UsingROSonWindows.md#shebang-in-ros-nodes).

Is this related to this question [here](https://answers.ros.org/question/326072/windows10-rosrun-couldnt-find-python-scripts-in-path-scripts/)?

Could someone give any clarification?

**Comment by ooeygui** [comment]
Thank you for the report. I think there was a regression in the rosrun.bat file - it should do a deep find on the script file. investigating.

**Comment by ooeygui** [comment]
This has been corrected in later builds

**Comment by ooeygui** [comment]
Reopening, as this appears to be broken on Noetic.

**Comment by IoTDan** [comment]
Please re-open if this still repros
