### ISSUE TITLE
[WinML] Post documentation on WinML ROS Node

### ISSUE THREAD

**Issue by ooeygui** [ms-iot/ROSOnWindows#17]
During ROSCon, we demonstrated hardware accelerated Windows Machine Learning with ROS. The repositories are accessible here:
https://github.com/ms-iot/winml_ros_demo
https://github.com/ms-iot/winml_tracker

However, we need to publish documentation, as well as make the Winml tracker download the onyx file.

**Comment by shschaefer** [comment]
Added basic documentation to WinML Tracker repository.  Will look at adding more documentation to the code.
