### ISSUE TITLE
Missing environment variables for ROS 2 on Windows

### ISSUE THREAD

**Issue by seanyen** [ms-iot/ROSOnWindows#199]
After `choco install ros-elquent-desktop -y --pre` and running `local_setup.bat`, all the environment should be all set and ready to use ROS 2. However, currently there are some environment variables missing.

## Workaround: (UPDATED on May/29/2020)

We made some progress to simplify the environment bootstrap after ROS 2 installation. However there are required [changes](https://github.com/colcon/colcon-core/pull/348) are not yet released by the upstream. As of today (May/29/2020), one more path is required to manually added to `%PATH%`, before running `local_setup.bat`.

```Batchfile
set "PATH=c:\opt\python37amd64;%PATH%"
call "c:\opt\ros\eloquent\x64\local_setup.bat"
```

**Comment by ooeygui** [comment]
Verified workaround

**Comment by seanyen** [comment]
Closing it for now. This is no longer required.
