### ISSUE TITLE
Communication with Ubuntu ROS on another device

### ISSUE THREAD

**Issue by zhangzhaoweii** [ms-iot/ROSOnWindows#204]
Describe the bug
Hi,I want to receive pointcloud2 message from another device which is using Ubuntu ROS，but there are no host and bashrc files in C:\opt\ros\melodic\x64. How can I set the hostname and IP in windows?

Expected behavior
Set the IP and hostname in ROSOnWindows .

Environment information:
 - OS version: windows10 1909(18363.720)
 - Chocolatey Versions: Chocolatey v0.10.15

Thanks in advance!

**Comment by ooeygui** [comment]
When you start the shell, you pass it a batch file. Today, we recommend you call directly into c:\opt\ros\melodic\x64\setup.bat. 

For your scenario, you'll instead make your own setup.bat file in your user account (say c:\user\zhangzhaoweii\setup_ros.bat), which looks something like this:
``` batch
call c:\opt\ros\melodic\x64\setup.bat
set ROS_IP=...
set ROS_MASTER_URI=http://<remote ip>:11311
```

and point your terminal.

Second, the Windows HOSTS file is located in `c:\Windows\System32\drivers\etc\hosts`. You can edit this from an Administrative command prompt.
