### ISSUE TITLE
[ROS2] "OSError: [WinError 193] %1" When Running "ros2 run rqt_console rqt_console"

### ISSUE THREAD

**Issue by songyuc** [ms-iot/ROSOnWindows#212]
**Describe the bug**
I am learning about ROS2 on Windows 10 today, 
and when I run `ros2 run rqt_console rqt_console`,
 an error appeared as:
> Traceback (most recent call last):
  File "E:\dev\ros2-eloquent\ros2-windows\Scripts\ros2-script.py", line 11, in <module>
    load_entry_point('ros2cli==0.8.7', 'console_scripts', 'ros2')()
  File "E:\dev\ros2-eloquent\ros2-windows\Lib\site-packages\ros2cli\cli.py", line 69, in main
    rc = extension.main(parser=parser, args=args)
  File "E:\dev\ros2-eloquent\ros2-windows\Lib\site-packages\ros2run\command\run.py", line 72, in main
    return run_executable(path=path, argv=args.argv, prefix=prefix)
  File "E:\dev\ros2-eloquent\ros2-windows\Lib\site-packages\ros2run\api\__init__.py", line 61, in run_executable
    process = subprocess.Popen(cmd)
  File "c:\python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**To Reproduce**
* Start a terminal and source the ROS2
* Run `ros2 run rqt_console rqt_console`

Then the error appeared.

**Expected behavior**
After running `ros2 run rqt_console rqt_console`, rqt_console program start normally.

**Environment information:**
 - OS version: `winver`-- 1909
 - Chocolatey Versions: `choco list --local-only`
```bash
Chocolatey v0.10.15
asio 1.12.1
chocolatey 0.10.15
chocolatey-core.extension 1.3.5.1
chocolatey-windowsupdate.extension 1.0.4
cmake 3.17.1
cmake.install 3.17.1
cunit 2.1.3
eigen 3.3.4
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
log4cxx 0.10.0
python 3.7.5
python3 3.7.5
tinyxml-usestl 2.6.2
tinyxml2 6.0.0
vcredist140 14.25.28508.3
vcredist2013 12.0.40660.20180427
20 packages installed.
```

**Comment by ooeygui** [comment]
If you install eloquent via the Microsoft chocolatey package (https://ms-iot.github.io/ROSOnWindows/GettingStarted/SetupRos2.html), rqt will start.

We have identified a new issue with rqt due to a libssl update. We'll be fixing it, but in the mean time you can do `set path=C:\opt\python37amd64\DLLs\;%path%` which allows rqt to load the libssl from the python path.
