### ISSUE TITLE
Does it support vs2017？

### ISSUE THREAD

**Issue by MicroYY** [ms-iot/ROSOnWindows#222]
I have installed it with vs2017. The main components of ROS, such as rviz works well. but when I create my package including "ros::init", there will be "unresolved external symbols" error .
And the catkin_make command fails too.  It seems that the static lib of ROS is not properly configured. So does rosonwindows support vs2017? In fact I want to directly use ros on my existing project, so is there any way to use it in vs?

**Comment by ooeygui** [comment]
Hello there,
The binaries we release for melodic are not compatible with Visual Studio 2017.

The melodic chocolatey packages are built with the v141 tool chain, which is included in vs2019. v141 is not binary compatible with v140 which was included in vs2017.

If you want to use ROS with v140, it is feasible, but you will have to build ROS and include it in your installation. We have instructions on how to build ROS here: https://ms-iot.github.io/ROSOnWindows/Build/source.html

Another solution I'd offer is to use the rosserial interface, which is a ROS-like over WinSocket. We used this approach with UWP as demonstrated in our WinML ROS Arm demo https://github.com/ms-iot/ros_winml_arm, where we used a ML pose detector and command and control from a UWP application.

Please reopen if you have issues.
