### ISSUE TITLE
Support Winget Deployment

### ISSUE THREAD

**Issue by ooeygui** [ms-iot/ROSOnWindows#223]
Microsoft has announced a package manager for Windows called Winget. We would like to support Winget for ROS deployments.

In order to deploy ROS and packages using Winget, the following needs to be done:

Winget must support .zip files
https://github.com/microsoft/winget-cli/issues/140

Winget must support Powershell scripts
https://github.com/microsoft/winget-cli/issues/299

**Comment by IoTDan** [comment]
moving to executable based deployments - so not supporting this.
