### ISSUE TITLE
vcpkg problem

### ISSUE THREAD

**Issue by sibinrsl1997** [ms-iot/ROSOnWindows#225]
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.6.0
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************

C:\Windows\System32>set ChocolateyInstall=c:\opt\chocolatey

C:\Windows\System32>choco source add -n=ros-win -s="https://roswin.azurewebsites.net/api/v2" --priority=1
Chocolatey v0.10.15
Nothing to change. Config already set.

C:\Windows\System32>choco upgrade ros-eloquent-desktop -y --execution-timeout=0 --pre
Chocolatey v0.10.15
Upgrading the following packages:
ros-eloquent-desktop
By upgrading you accept licenses for the packages.
ros-eloquent-desktop is not installed. Installing...
Progress: Downloading ros-eloquent-desktop 20200530.1-pre... 100%
Progress: Downloading ros-eloquent-desktop 20200530.1-pre... 100%

ros-eloquent-desktop v20200530.1-pre
ros-eloquent-desktop package files upgrade completed. Performing other installation steps.
Deploying vcpkg...
ERROR: remove C:\opt\vcpkg and reinstall again.
The upgrade of ros-eloquent-desktop was NOT successful.
Error while running 'c:\opt\chocolatey\lib\ros-eloquent-desktop\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (c:\opt\chocolatey\logs\chocolatey.log).

Failures
 - ros-eloquent-desktop (exited -1) - Error while running 'c:\opt\chocolatey\lib\ros-eloquent-desktop\tools\chocolateyInstall.ps1'.
 See log for details.

C:\Windows\System32>
please give a solution

**Comment by seanyen** [comment]
@sibinrsl1997 The installation found an existing `c:\opt\vcpkg` folder but which doesn't have an expected `vcpkg.exe`. Can you move the folder or delete it, then retry again?
