### ISSUE TITLE
TypeError in rosfindpath.py when using roscd

### ISSUE THREAD

**Issue by Brac24** [ms-iot/ROSOnWindows#248]
When running roscd roscpp I get a type error in rosfindpath.py on line 74 in which it expects an str object but instead gets a bytes object.
![image](https://user-images.githubusercontent.com/4980091/86994659-d6e8ff00-c15b-11ea-861c-74b417455f69.png)

This is the line the caused the error
![image](https://user-images.githubusercontent.com/4980091/86994901-845c1280-c15c-11ea-9a55-fdeed4cc05bc.png)

I identified that the culprit was the package_dir variable and investigated further where this variable was set which is line 69 by calling ros_location_find(package_name)
![image](https://user-images.githubusercontent.com/4980091/86995050-e3218c00-c15c-11ea-897a-7d0953858503.png)

The return value result_location in the ros_location_find() method is what is setting the package_dir. The result_location variable is being set on either line 40 or 46 which uses the communicate() method which says that by default input and output will be in bytes.
![image](https://user-images.githubusercontent.com/4980091/86995379-b621a900-c15d-11ea-95bf-86b1aa686361.png)

If I decode package_dir this error is fixed
![image](https://user-images.githubusercontent.com/4980091/86995422-da7d8580-c15d-11ea-809a-e72465948626.png)

The roscd.bat file also tries to change directories doing: cd \d "%target_path%".
This would give me the below error.
![image](https://user-images.githubusercontent.com/4980091/86995752-c4bc9000-c15e-11ea-85d6-f4bc2523b648.png)
Here I was debugging by printing the %target_path% variable that the batch file is using and then it gives me the error.

Removing the \d fixed this error for me.

The error is essentially fixed for me I just don't know if these changes would be acceptable or if there is a different issue going on.

-----------------------------------------------------------------
Installed ROS noetic

Ran setup.bat as described in tutorials many of the commands are working.

I am using the Windows Terminal app with the below commandline setting in settings.json:
"C:\\Windows\\System32\\cmd.exe /k \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools\\VsDevCmd.bat\" -arch=amd64 -host_arch=amd64 && set ChocolateyInstall=c:\\opt\\chocolatey&& c:\\opt\\ros\\noetic\\x64\\setup.bat"

This error occurred regardless if it was command prompt or Windows Terminal.

Catkin workspace is under C:\Users\brac2\~\catkin_ws 
(was trying to follow the linux tutorial hence the ~)
ran catkin_make and everything built correctly

Using rospack find roscpp returned the correct path

Then tried using roscd roscpp to go to that path and it failed

Expected when using roscd roscpp to go into the path:
C:\opt\ros\noetic\x64\share\roscpp

-----------------------------------------------------------------------
Environment
ROS noetic
Windows 10 Home Version 1909 (OS Build 18363.900)
Chocolatey v0.10.15

**Comment by ooeygui** [comment]
Thank you for the detailed report!

**Comment by lilustga** [comment]
Closing issue as the fix is now in Noetic
