### ISSUE TITLE
SDL2 fails to install in daily foxy build

### ISSUE THREAD

**Issue by lilustga** [ms-iot/ROSOnWindows#259]
**Describe the bug**
sdl2 fails to install. The following appears in the console during installation of dependencies:
`command return code [vcpkg install sdl2 --triplet x64-windows]: 1`

Occurs in the daily foxy-desktop build

**Comment by seanyen** [comment]
This should be addressed and fixed in ros-foxy-desktop 20200912.0.0.2009161641. Closing it now.
