### ISSUE TITLE
No handler could be found for logger "rosout"

### ISSUE THREAD

**Issue by raviBhadeshiya** [ms-iot/ROSOnWindows#26]
When I try to run roscore on Ubuntu 16.04 and export to windows 10 pro for workstation; I'm getting this error. Am I missing something? Or is it  related to slow connection with rosout?
![err](https://user-images.githubusercontent.com/5351081/47316840-b25a9580-d60d-11e8-99d1-acc9572f6ebb.png)

**Comment by ooeygui** [comment]
Hi Ravi,
We have this logged as Issue #13 . This is one of the things we need to fix before committing upstream. For now, it can be ignored.

**Comment by raviBhadeshiya** [comment]
Hi Lou, I'm unable to communicate between windows and ubuntu as well.
