### ISSUE TITLE
[Noetic] site-packages\extra.pth can throw error if directory in PATH does not exist

### ISSUE THREAD

**Issue by ooeygui** [ms-iot/ROSOnWindows#262]
Python 3.8 no longer supports the system path for resolving dependencies. To work around this, code was added to the noetic environment to prop the system path to python for resolution.

If you have a directory in your environment which does not exist, this can error.

Workaround:
Remove invalid directories from your system path.

**Comment by seanyen** [comment]
This was addressed in the v20200831.0.0.2009101215 release and should be fixed. Closing it.
