### ISSUE TITLE
[Noetic] vcpkg path is missing from default install

### ISSUE THREAD

**Issue by ooeygui** [ms-iot/ROSOnWindows#278]
** Bug **
`ros-noetic-desktop_full 20200831.0.0.2009101215`

The vcpkg hook is missing from the catkin workspace, which prevents vcpkg from being used for rosdep resolution.

**Comment by seanyen** [comment]
This should be addressed in `ros-noetic-desktop_full 20200918.0.0.2009302316`. Closing it now.
