### ISSUE TITLE
[MoveIt][ROS1] Support warehouse_ros_mongo

### ISSUE THREAD

**Issue by ooeygui** [ms-iot/ROSOnWindows#284]
The Azure Edge Robotics team has had customer requests to support warehouse_ros_mongo on Windows, which has been reflected on that repo (https://github.com/ros-planning/warehouse_ros_mongo/issues/33). 

We are investigating:

* The driver appears to be using a legacy version of the API.
* We would be moving that to use https://github.com/microsoft/vcpkg/tree/master/ports/mongo-cxx-driver.

**Comment by ooeygui** [comment]
https://github.com/ros-planning/warehouse_ros_mongo/issues/66

**Comment by IoTDan** [comment]
we will not be supporting warehouse_ros_mongo. we will look at other options
