### ISSUE TITLE
[rosservice] rosservice does not de-register

### ISSUE THREAD

**Issue by kejxu** [ms-iot/ROSOnWindows#3]
after shutdown of turtlesim, the xmlrpc server still advertises the endpoint address.

run rosnode ping turtlesim  and you will see the entry remains.

Repro steps:
console 1: run 'roscore'
console 2: run 'rosrun turtlesim turtlesim_node', turtle window shown
console 3: run 'rosnode list'

press Ctrl-C in console 2, turtle window disappear but prompt will not show up.  If close the console, the entry will not be clean up.  If close turtlesim by clicking the close button on the turtle window, the service de-register correctly.

**Comment by seanyen** [comment]
This is no longer reproducible. Using `ctrl-c` can shutdown the `rosrun` correctly. I am closing it now.
