### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found

### ISSUE THREAD

**Issue by WestbrookZero** [ms-iot/ROSOnWindows#305]
**Describe the bug**
qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: direct2d, minimal, offscreen, windows..

**Environment information:**
 - OS version: `win10`

**Comment by seanyen** [comment]
@WestbrookZero Thanks for reporting this issue. Can you also specify what distro (e.g., Melodic, Noetic, or Foxy) and some steps how you run into this?

**Comment by WestbrookZero** [comment]
Thanks for your answer! 
![image](https://user-images.githubusercontent.com/13358789/103146673-dd117d00-4787-11eb-8a6c-be64ad954893.png)
![image](https://user-images.githubusercontent.com/13358789/103146674-e1d63100-4787-11eb-85ff-a4444cc3bd63.png)
I use Melodic on win10, i set environment path :
Path
C:\opt\ros\melodic\x64\bin
QT_PLUGIN_PATH
C:\opt\ros\melodic\x64\plugins
QT_QPA_PLATFORM_PLUGIN_PATH
C:\opt\ros\melodic\x64\plugins\platforms
when i start "x64 Native Tools Command Prompt for VS 2019",Run as Administrator，as below：
cd C:\opt\ros\melodic\x64
setup.bat
rosrun rviz rviz
i still have the error: 
qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "C:\opt\ros\melodic\x64\plugins\platforms;" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: direct2d, minimal, offscreen, windows.

**Comment by IoTDan** [comment]
fixed in noetic.
