### ISSUE TITLE
Cant launch display window Gazebo

### ISSUE THREAD

**Issue by wlawler45** [ms-iot/ROSOnWindows#320]
I have been trying to run Gazebo on ROS for Windows, I run gzserver.exe and it seems to launch the node fine, but then when I run gzclient.exe --verbose I get the following:

[Msg] Could not load the Qt platform plugin "windows" in "" even though it was found.
[Err] [D:\ws\src\gazebo\gazebo10\gazebo\gui\GuiIface.cc:123] This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: direct2d, minimal, offscreen, windows.

I'm not sure what to do about this issue.

I am on Windows 10, noetic install.

@johnwason

**Comment by IoTDan** [comment]
It looks like you are trying to build Gazebo 10, instead of the built in Gazebo 9 on noetic. Unfortunately this is not a supported configuration. we are looking at supporting future versions of Gazebo (like Gazebo 11) on ROS2.
