### ISSUE TITLE
Test & document Visibility Control Header with static built libraries

### ISSUE THREAD

**Issue by lilustga** [ms-iot/ROSOnWindows#323]
Test a change to the Symbol Visibility Control Header to accommodate building code as a static library. The export macros will be blank in the case of a static library.

The change is discussed in this comment thread:
https://github.com/ms-iot/ROSOnWindows/pull/322#discussion_r595002284

**Comment by traversaro** [comment]
To clarify, I usually suggest to support the static usecase for standalone libraries so that they can be easily packaged inside vcpkg (https://github.com/Microsoft/vcpkg) for all the official supported triplets.

**Comment by ooeygui** [comment]
https://ms-iot.github.io/ROSOnWindows/Porting/SymbolVisibility.html

**Comment by ooeygui** [comment]
We need to move our symbol visibility doc to ROS.org. And add the CMake doc

**Comment by IoTDan** [comment]
fixed - documented and published
