### ISSUE TITLE
Has anyone successfully downloaded and compiled sbpl thru ROS on Windows?

### ISSUE THREAD

**Issue by Smitty-44** [ms-iot/ROSOnWindows#335]
Hi there,
I have ROS on Windows on my desktop for over a year and a half.  I have Melodic installed.  I am downloading and installing/compiling ROBOTIS OP3 open source code to run with a biped I have created.  One piece of the software is sbpl.  It is not really a package per se.  But it is used with SLAM and path planning, etc.  There are installation instructions and they are old, but they are also for linux.
[https://github.com/sbpl/sbpl/blob/master/README.txt](url)
I made it to the very end of step 1.1, with the last step issuing "make".  Since I can't do that, the library is not built.
Does anyone know of a solution or ideas to adding sbpl into ROS on Windows?
Thank you for any assistance,
Jay

**Comment by IoTDan** [comment]
porting cook book exists here: https://ms-iot.github.io/ROSOnWindows/Porting/Cookbook.html
