### ISSUE TITLE
Visual Studio Community 2019 no longer available.

### ISSUE THREAD

**Issue by KeithGal** [ms-iot/ROSOnWindows#356]
All Visual Studio Community downloads point to the 2022 version, which is not supported by ROS yet.

I have just setup a new PC and can't build anything.

  File "c:\opt\ros\foxy\x64\lib\site-packages\colcon_cmake\task\cmake\build.py", line 162, in _reconfigure
    raise RuntimeError(
RuntimeError: Unknown / unsupported VS version '17.0'

**Comment by KeithGal** [comment]
Partial answer:

If CMake is updated to the latest version, then newly created packages can be built as they default to VS 2022 and the latest CMake version supports this.

However old packages still can't be rebuilt.

**Comment by ooeygui** [comment]
Visual Studio 2019 is available in the older downloads section - https://visualstudio.microsoft.com/vs/older-downloads/. I'll update the docs.

**Comment by ooeygui** [comment]
The default toolchains are the important part.

**Comment by ooeygui** [comment]
I updated ros.org for ROS1 and fixed out ROS2 docs - https://github.com/ms-iot/ROSOnWindows/pull/357.

**Comment by KeithGal** [comment]
Thankyou, I did look but obviously not hard enough.

**Comment by IoTDan** [comment]
Per @ooeygui comments above
