### ISSUE TITLE
[catkin_make] How to add PCL dependency for ROS

### ISSUE THREAD

**Issue by bbw2008927** [ms-iot/ROSOnWindows#46]
**Describe the issue**
There are some code based on PCL and VS2017, and I want plant them into ROS.
I found out the PCL_percetion package is not ready. So I have to use PCL from PCL-1.8.1-AllInOne-msvc2017-win64.exe.
My question is how to config local library in ROS-windows.
In Linux side, find_package will help.  But in windows side, I don't know how to make catkin to find local library.

**Discuss solution**
I'm newer for cmake, would you please give me some advice.
I guess maybe there are two way:
1. Can I copy all the lib of PCL into C:\opt\rosdeps\x64\lib
             copy all the h of PCL into C:\opt\rosdeps\x64\include
             and set all necessary bin into PATH of OS.
2. In the Cmake file to set include folder, library folder and name of lib.
  include_directories to add include folder.
  LINK_DIRECTORIES to add library folder.
 LINK_LIBRARIES to add lib file name.

I only try way 2. I find out boost from PCL conflict with boost in rosdep.

**Comment by seanyen-msft** [comment]
@bbw2008927 have you tried to install ros-melodic-desktop_full instead? pcl_conversions should be ready there.

**Comment by bbw2008927** [comment]
Hi 
Thanks for your response.
I have install ros-melodic-desktop-full. 
Besides,  pcl_conversions only provide function to convert PCL to ROS_message.
pcl_conversion don't contain any Lidar process function.
So far, I use vcpkg to manage package including OpenCV, PCL. and vcpkg will handle cmake config.
Take OpenCV as example, following should be added if you use vcpkg:


find_package(OpenCV REQUIRED)
add_executable(cvbridge_img src/cvbridge_img.cpp)
target_include_directories(cvbridge_img PRIVATE ${OpenCV_INCLUDE_DIRS})
target_link_libraries(cvbridge_img ${catkin_LIBRARIES} ${OpenCV_LIBS})


I want to say, It looks like Microsoft is building a complete env. 
It should be a manual tell developer  how to switch Linux back into Windows.
Happy new year

**Comment by bbw2008927** [comment]
Sorry, I make mistake.
The command is choco update ros-melodic-desktop_full -y
And  it looks like this full version contain pcl 1.8.1 and freeimage library.
These two can used to process lidar and image.
