### ISSUE TITLE
Robot_state_publisher dies on an invalid URDF

### ISSUE THREAD

**Issue by ooeygui** [ms-iot/ROSOnWindows#50]
**Describe the bug**
robot_state_publisher does not handle the parse error from urdf model parsing, instead crashes without an error description.

**To Reproduce**
Create a URDF with an invalid link; such as two roots.
```
<?xml version="1.0" ?>

<robot name="sample" xmlns:xacro="http://ros.org/wiki/xacro">
    <link name="camera_frame"/>
    <link nmae="foo" />
</robot>
```

Then use urdf_tutorial to run this:
roslaunch urdf_tutorial display.launch model:=sample_ws\urdf\workcell.xacro

**Expected behavior**
robot_state_publisher should output an error instead of crashing

**Comment by gavanderhoorn** [comment]
This may actually be an upstream issue: https://github.com/ros/robot_state_publisher/issues/81.

**Comment by ooeygui** [comment]
Closing as an upstream issue
