### ISSUE TITLE
rosrun does not work with camera calibration

### ISSUE THREAD

**Issue by ooeygui** [ms-iot/ROSOnWindows#53]
Working through the camera calibration tutorial, rosrun cannot find the installed calibration python script.
http://wiki.ros.org/camera_calibration/Tutorials/MonocularCalibration

Using the command
`rosrun camera_calibration cameracalibrator.py --size 8x6 --square 0.0245 image:=/cv_camera/image_raw camera:=/cv_camera`

I receive the error:
`[rosrun] Couldn't find executable named cameracalibrator.py`

rospack shows 
`camera_calibration C:/opt/ros/melodic/x64\share\camera_calibration`
but this location only has a package.xml.

I suspect that rosrun should also look in the lib\site-packages

**Comment by dejongyeong** [comment]
Hi. I would like to know is that solved? I'm facing the same issue as well

**Comment by ooeygui** [comment]
This bug was that rosrun could not find the python file. We have fixed that problem. (Verified today)

Can you share more information? What do you see in the console?

**Comment by dejongyeong** [comment]
@ooeygui When I try to run the command, it gave me this:
![image](https://user-images.githubusercontent.com/22542203/79157272-39846600-7dcc-11ea-96d9-3f4d859efbd0.png)

and in the folder, there's no python file.
![image](https://user-images.githubusercontent.com/22542203/79157338-5456da80-7dcc-11ea-95f4-d469b8d878fd.png)

Thanks.

**Comment by ooeygui** [comment]
That looks like WSL, not Native ROS on Windows. You cannot run UI applications like calibration in WSL. check out http://aka.ms/ros for running ros on windows.
