### ISSUE TITLE
Error while building: Could NOT find gazebo_ros

### ISSUE THREAD

**Issue by amitbiswas26** [ms-iot/ROSOnWindows#60]
Hi, I am getting this error while trying to build (_catkin_make install -DCMAKE_BUILD_TYPE=RelWithDebInfo_):
This is on a fresh machine, just finished installing ROS Win, and was trying to run the Turtle bot simulation.

```
-- Could NOT find gazebo_ros (missing: gazebo_ros_DIR)
-- Could not find the required component 'gazebo_ros'. 
```

![gazebo error](https://user-images.githubusercontent.com/38895485/51427558-36d99780-1bae-11e9-9539-7c53c3ee3ff5.PNG)

**Comment by seanyen-msft** [comment]
@amitbiswas26 Did you `choco upgrade ros-melodic-desktop_full -y`? And checking `choco list -lo` and `rospack list` would help identify the missing modules.

**Comment by amitbiswas26** [comment]
@seanyen-msft Thanks, `choco upgrade ros-melodic-desktop_full -y` seems to have fixed it. Should we add it in the instructions [here ](https://ms-iot.github.io/ROSOnWindows/Turtlebot/Turtlebot3.html)before the Build Nodes section?

**Comment by seanyen-msft** [comment]
@amitbiswas26 I added few lines in Build Notes. Hope that helps!

**Comment by amitbiswas26** [comment]
@seanyen-msft Thanks

**Comment by seanyen-msft** [comment]
Sounds like it's resolved. Closed it.
