### ISSUE TITLE
RViz does not display Temperature

### ISSUE THREAD

**Issue by lrapetti** [ms-iot/ROSOnWindows#66]
**Describe the bug**
When I try to add a `TemperatureDisplay`, I am getting the following error:
```
GLHardwareVertexBuffer::lock - Error: failed to Discard the buffer
```
![51304855-8e0a2b80-1a39-11e9-9a52-c56d4b06ff7b](https://user-images.githubusercontent.com/35487806/52055440-b462b780-255f-11e9-8876-11360860ea6e.png)

I see a similar error was described in #49, where it seem to be related to driver 

**Device information**
- Graphic Processor: Intel HD Graphics 630
- Graphic Diver: Intel HD Graphics Driver 23.20.16.4973

**Comment by seanyen-msft** [comment]
@lrapetti Thanks for reporting. Have you tried to update the graphic driver to the latest to see if the issue goes away? https://downloadcenter.intel.com/product/98909/Intel-HD-Graphics-630

**Comment by lrapetti** [comment]
@seanyen-msft From the device manager it seems I'm on the latest version. 
If I try to manually download and install the latest version of the driver from the link you sent me (`25.20.100.6519`), the installation procedure fails with the following error message: `The driver being installed is not validated for this computer. Please obtain the appropriate driver from the computer manufacturer`.

Some further information on the computer:
- OS: `Microsoft Windows 10 Pro 10.0.17134 Build 17134`
- Model: `Dell Precision 5520`

**Comment by traversaro** [comment]
@seanyen I see tha the issue still has the `more-information-needed`, feel free to let us know (I work in the same lab of @lrapetti) any additional information you think it could make sense to provide, thanks a lot!

**Comment by seanyen** [comment]
@traversaro Thanks for the reminder!

@lrapetti, do you have a chance to update your machine drivers? https://www.dell.com/support/home/ca/en/cabsdt1/product-support/product/precision-15-5520-laptop/drivers

Also, is the issue about RViz not able to display temperature or "GLHardwareVertexBuffer::lock - Error: failed to Discard the buffer" problem? Sharing `rviz` configuration file might be also helpful.

**Comment by lrapetti** [comment]
> Also, is the issue about RViz not able to display temperature or `GLHardwareVertexBuffer::lock - Error: failed to Discard the buffer` problem?

The error I see is `GLHardwareVertexBuffer::lock - Error: failed to Discard the buffer`, and at the same time the temperature does not shown.

> Sharing `rviz` configuration file might be also helpful.

The `rviz` configuration can be found at https://github.com/robotology/human-dynamics-estimation/blob/master/conf/ros/rviz/HDERviz.rviz, and it has been tested on a different machine (non Windows) and the temperature showed up correctly as in the sphere that you can see in the following screenshot:
![Screen Shot 2019-06-26 at 14 45 54](https://user-images.githubusercontent.com/35487806/60180820-2c888d00-9821-11e9-86cb-c7ee1ac88c6b.png)

**Comment by lrapetti** [comment]
> @lrapetti, do you have a chance to update your machine drivers? https://www.dell.com/support/home/ca/en/cabsdt1/product-support/product/precision-15-5520-laptop/drivers

I have also tried to update the machine drivers, but nothing changed.

**Comment by seanyen** [comment]
@lrapetti @traversaro  Sorry for super long overdue on this issue. I think I am able to find a environment to repro this issue, and would like to check if my observation matches to what you saw.

So currently the ROS on Windows is using `OGRE 1.10.11` as the rendering backend, and in my repro case (I am using `Intel UHD 630`), the visualization of temperature only works when the styles are "Point", "Square" and "Sphere".

Does that match to what the original problems reported here?

And just for your information, after I switched to use OGRE 1.12.6 and did a private RViz build. It seems that the temperature display can work for all styles. Atm, I think there is that the newer version of OGRE comes with some improvement which can help this case.

**Comment by lrapetti** [comment]
> the visualization of temperature only works when the styles are "Point", "Square" and "Sphere".
> 
> Does that match to what the original problems reported here?

we are actually trying to visualize the temperature on spheres, like in the picture in https://github.com/ms-iot/ROSOnWindows/issues/66#issuecomment-505860273 (obtained on a different machine)

**Comment by seanyen** [comment]
Since the behavior depends on an external library, I am closing it. For anyone hitting this issue, you can use Noetic release which is using the OGRE 1.12 as the backend, and which comes with the more recent bug fixes.
