### ISSUE TITLE
choco upgrade ros-melodic-desktop_full does not upgrade rosdeps

### ISSUE THREAD

**Issue by ooeygui** [ms-iot/ROSOnWindows#68]
We recently made a change to rViz which requires the new ogre release. When upgrading in-place, the new ogre drop is not brought in. This leads to a build break when compiling rViz plugins, like MoveIt.

Workaround:
choco upgrade all

**Comment by seanyen** [comment]
The ROS dependencies and ROS itself are in the single installer package (inno setup), and this should be no longer a problem for upgrading.
