### ISSUE TITLE
image_transport_plugins missing from ros-melodic-desktop

### ISSUE THREAD

**Issue by ooeygui** [ms-iot/ROSOnWindows#86]
Some sensor drivers require image_transport_plugins in order to transmit data. For example, realsense2 requires this plugin.

Please add https://github.com/ms-iot/image_transport_plugins to ros-melodic-desktop

**Comment by seanyen** [comment]
It now should be part of the `ros-melodic-desktop` choco package. Please try it out and let me know any issues.
